import os
from os.path import abspath, dirname, join

from invoke import task
from robot.libdoc import libdoc

assert os.getcwd() == dirname(abspath(__file__))


@task
def keyword_documentation(ctx):
    """Generates the library keyword documentation

    Documentation is generated by using the Libdoc tool.
    """
    libdoc(join('src', 'SeleniumLibrary'), join('docs', 'SeleniumLibrary.html'))
